replicaCount: 1

image:
  repository: 106342565607.dkr.ecr.eu-north-1.amazonaws.com/brain-tumor-backend
  tag: latest
  pullPolicy: Always

service:
  type: ClusterIP
  port: 8000

resources:
  requests:
    cpu: 200m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi

hpa:
  enabled: true
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 70

configMapName: backend-config

config:
  port: 8000
  frontend: "../brain-tumor-vue/dist"

existingSecret: backend-db-url
