/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Chat: typeof import('./src/components/Chat.vue')['default']
    Dashboard: typeof import('./src/components/Dashboard.vue')['default']
    IconBrainLogo: typeof import('./src/components/icons/IconBrainLogo.vue')['default']
    IconChat: typeof import('./src/components/icons/IconChat.vue')['default']
    IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
    IconHome: typeof import('./src/components/icons/IconHome.vue')['default']
    IconLogin: typeof import('./src/components/icons/IconLogin.vue')['default']
    IconLogout: typeof import('./src/components/icons/IconLogout.vue')['default']
    IconPhotoAnalyze: typeof import('./src/components/icons/IconPhotoAnalyze.vue')['default']
    IconPhotoResult: typeof import('./src/components/icons/IconPhotoResult.vue')['default']
    IconRegister: typeof import('./src/components/icons/IconRegister.vue')['default']
    IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
    LoginDialog: typeof import('./src/components/LoginDialog.vue')['default']
    LogoutDialog: typeof import('./src/components/LogoutDialog.vue')['default']
    PhotoAnalyzer: typeof import('./src/components/PhotoAnalyzer.vue')['default']
    PhotoResultEditor: typeof import('./src/components/PhotoResultEditor.vue')['default']
    PhotoResultViewer: typeof import('./src/components/PhotoResultViewer.vue')['default']
    RegisterDialog: typeof import('./src/components/RegisterDialog.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
